const TOGGLE_THEME = 'TOGGLE_THEME';
const TOGGLE_MEMBER = 'TOGGLE_MEMBER';

const DISPLAY_ALERT = 'DISPLAY_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';

const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export {
  TOGGLE_THEME,
  TOGGLE_MEMBER,
  SETUP_USER_BEGIN,
  SETUP_USER_SUCCESS,
  SETUP_USER_ERROR,
  DISPLAY_ALERT,
  CLEAR_ALERT,
};
